---
# Cloudwatch Exporter metrics configuration (cloudwatch_metrics.yml)
cloudwatch_metrics_enable: true
auto_scaling: no
billing: no
custom: no
dynamo_db: no
ebs: true
ec2: true
elasti_cache: no
events: no
lambda: no
logs: no
network_elb: no
rds: no
s3: true
transit_gateway: no
trusted_advisor: no
usage: no
